# Generated by Django 2.0.9 on 2018-10-27 16:13

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Coordenadas'),
        ),
    ]
