# Generated by Django 2.0.9 on 2018-10-27 16:38

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181027_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='geolocation2',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Coordenada Final'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Coordenada Inicio'),
        ),
    ]
